(() => {
  "use strict";
  const API_URL = String(window.RIO_INCIDENTES_API_URL || "").trim();
  const STORE_KEY = "rio_incidentes_v1";
  let tickets = [], selected = null, assignee = null;
  const PADRON_URL = "../../data/ASISTENCIA_RIO%20-%20PADRON.csv";
  const padron = new Map();
  const $ = s => document.querySelector(s);
  const els = { rows:$("#ticketRows"), empty:$("#emptyState"), count:$("#resultCount"), search:$("#searchInput"), status:$("#statusFilter"), branch:$("#branchFilter"), priority:$("#priorityFilter"), dialog:$("#ticketDialog"), badge:$("#connectionBadge") };

  document.addEventListener("DOMContentLoaded", async () => { bind(); await loadPadron(); loadTickets(); });
  function bind(){
    [els.search,els.status,els.branch,els.priority].forEach(x=>x.addEventListener("input",render));
    $("#refreshButton").addEventListener("click",loadTickets);
    $("#saveButton").addEventListener("click",saveTracking);
    $("#detailAssigneeCode").addEventListener("input",matchAssignee);
  }
  async function loadPadron(){try{const response=await fetch(PADRON_URL,{cache:"no-store"});if(!response.ok)throw new Error("Padrón no disponible");const lines=(await response.text()).replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean);const headers=parseCsvLine(lines.shift()).map(norm);const idIndex=headers.indexOf("vendedor_id"),nameIndex=headers.indexOf("apellido_nombre"),branchIndex=headers.indexOf("sucursal_base"),roleIndex=headers.indexOf("rol");lines.forEach(line=>{const cols=parseCsvLine(line);const code=String(cols[idIndex]||"").trim();if(code)padron.set(code,{code,name:String(cols[nameIndex]||"").trim(),branch:String(cols[branchIndex]||"").trim(),role:String(cols[roleIndex]||"").trim()})})}catch(error){console.error(error)}}
  function parseCsvLine(line){const result=[];let value="",quoted=false;for(let i=0;i<line.length;i++){const char=line[i];if(char==='"'&&quoted&&line[i+1]==='"'){value+='"';i++}else if(char==='"'){quoted=!quoted}else if(char===','&&!quoted){result.push(value);value=""}else value+=char}result.push(value);return result}
  async function loadTickets(){
    try{
      if(!API_URL) throw new Error("local");
      const res=await fetch(`${API_URL}?action=listar&t=${Date.now()}`,{cache:"no-store"}); const data=await res.json();
      if(!res.ok||!data.ok) throw new Error(data.error||"No se pudo cargar");
      tickets=Array.isArray(data.tickets)?data.tickets:[]; els.badge.textContent="Conectado"; els.badge.classList.add("online");
    }catch(error){ tickets=readLocal(); els.badge.textContent=API_URL?"Sin conexión · datos locales":"Modo local"; els.badge.classList.remove("online"); }
    fillBranches(); render();
  }
  function fillBranches(){const current=els.branch.value;const values=[...new Set(tickets.map(x=>x.branch).filter(Boolean))].sort();els.branch.innerHTML='<option value="">Todas</option>'+values.map(option).join("");els.branch.value=values.includes(current)?current:""}
  function filtered(){const q=norm(els.search.value);return tickets.filter(t=>(!q||norm([t.id,t.title,t.description,t.branch,t.reporterCode,t.assignee,t.area].join(" ")).includes(q))&&(!els.status.value||t.status===els.status.value)&&(!els.branch.value||t.branch===els.branch.value)&&(!els.priority.value||t.priority===els.priority.value))}
  function render(){const rows=filtered();els.rows.innerHTML="";els.empty.hidden=rows.length>0;els.count.textContent=`${rows.length} incidente${rows.length===1?"":"s"}`;rows.forEach(t=>{const tr=document.createElement("tr");tr.className="ticket-row";tr.innerHTML=`<td><span class="ticket-id">${esc(t.id)}</span><strong class="ticket-title">${esc(t.title)}</strong><small>${esc(t.area||"")}</small></td><td>${esc(t.branch)}</td><td><span class="pill priority-${esc(t.priority)}">${esc(t.priority)}</span></td><td><span class="pill">${esc(t.status)}</span></td><td>${esc(t.assignee||"Sin asignar")}</td><td>${date(t.updatedAt)}</td>`;tr.addEventListener("click",()=>openTicket(t));els.rows.appendChild(tr)});metrics()}
  function metrics(){const today=new Date().toDateString();$("#pendingMetric").textContent=tickets.filter(t=>["Abierto","En proceso"].includes(t.status)).length;$("#progressMetric").textContent=tickets.filter(t=>t.status==="En proceso").length;$("#criticalMetric").textContent=tickets.filter(t=>t.priority==="Crítica"&&t.status!=="Cerrado").length;$("#resolvedMetric").textContent=tickets.filter(t=>t.status==="Resuelto"&&new Date(t.updatedAt).toDateString()===today).length}
  function openTicket(t){selected=t;$("#detailId").textContent=t.id;$("#detailTitle").textContent=t.title;$("#detailDescription").textContent=t.description;$("#detailStatus").value=t.status;$("#detailAssigneeCode").value=t.assigneeCode||"";$("#detailNote").value="";$("#saveMessage").textContent="";$("#detailMeta").innerHTML=meta("Sucursal",t.branch)+meta("Prioridad",t.priority)+meta("Área",t.area)+meta("Colaborador",t.reporterCode)+meta("Creado",date(t.createdAt))+meta("Actualizado",date(t.updatedAt));const files=t.attachments||[];$("#attachmentSection").hidden=!files.length;$("#detailAttachments").innerHTML=files.map(f=>`<a href="${esc(f.url||f.dataUrl||"#")}" target="_blank" rel="noopener">${esc(f.name)}</a>`).join("");matchAssignee();renderHistory(t);els.dialog.showModal()}
  function renderHistory(t){const history=Array.isArray(t.history)?t.history:[];$("#detailHistory").innerHTML=history.length?history.slice().reverse().map(h=>`<article><strong>${esc(h.status||"Actualización")}${h.assignee?` · ${esc(h.assigneeCode?`Cód. ${h.assigneeCode} · `:"")}${esc(h.assignee)}`:""}</strong><p>${esc(h.note||"Cambio de estado o responsable")}</p><time>${date(h.at)}</time></article>`).join(""):'<p class="muted">Todavía no hay notas de seguimiento.</p>'}
  function matchAssignee(){const code=$("#detailAssigneeCode").value.replace(/\D/g,"");$("#detailAssigneeCode").value=code;assignee=padron.get(code)||null;const hint=$("#assigneeMatch");if(!code){hint.textContent="Ingresá un código del padrón.";hint.className=""}else if(!padron.size){hint.textContent="No se pudo cargar el padrón.";hint.className="match-error"}else if(!assignee){hint.textContent="Código no encontrado en el padrón.";hint.className="match-error"}else{hint.textContent=`${assignee.name}${assignee.branch?` · ${assignee.branch}`:""}${assignee.role?` · ${assignee.role}`:""}`;hint.className="match-ok"}}
  async function saveTracking(){if(!selected)return;matchAssignee();const button=$("#saveButton"),message=$("#saveMessage");const code=$("#detailAssigneeCode").value.trim();if(!code||!assignee){message.className="save-message error";message.textContent="Ingresá un código válido del padrón para identificar al responsable.";return}const payload={action:"actualizar",id:selected.id,status:$("#detailStatus").value,assigneeCode:assignee.code,assignee:assignee.name,note:$("#detailNote").value.trim()};button.disabled=true;message.className="save-message";message.textContent="Guardando…";try{let updated;if(API_URL){const res=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(payload)});const data=await res.json();if(!data.ok)throw new Error(data.error||"No se pudo actualizar");updated=data.ticket}else{updated=updateLocal(payload)}tickets=tickets.map(t=>t.id===updated.id?updated:t);saveLocal();selected=updated;message.textContent="Seguimiento guardado.";$("#detailNote").value="";renderHistory(updated);render()}catch(error){message.className="save-message error";message.textContent=error.message}finally{button.disabled=false}}
  function updateLocal(p){const now=new Date().toISOString();const history=Array.isArray(selected.history)?selected.history.slice():[];history.push({at:now,status:p.status,assigneeCode:p.assigneeCode,assignee:p.assignee,note:p.note});return{...selected,status:p.status,assigneeCode:p.assigneeCode,assignee:p.assignee,updatedAt:now,history}}
  function readLocal(){try{return JSON.parse(localStorage.getItem(STORE_KEY)||"[]")}catch{return[]}}function saveLocal(){localStorage.setItem(STORE_KEY,JSON.stringify(tickets))}
  function meta(label,value){return`<div><span>${label}</span><strong>${esc(value||"-")}</strong></div>`}function option(v){return`<option>${esc(v)}</option>`}function norm(v){return String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase()}function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}function date(v){const d=new Date(v);return isNaN(d)?"-":new Intl.DateTimeFormat("es-AR",{dateStyle:"short",timeStyle:"short"}).format(d)}
})();
